# Available in rust nightly from 2023-07-18
[target.sparc-unknown-none-elf]
# Either tool should work as a linker
# linker = "sparc-gaisler-elf-clang"
linker = "sparc-gaisler-elf-gcc"
runner = "tsim-leon3 -c sim-commands.txt"

[build]
target = ["sparc-unknown-none-elf"]
rustflags = "-Ctarget-cpu=leon3"

[unstable]
build-std = ["core"]
