# Available in rust nightly from 2023-07-18
[target.sparc-unknown-none-elf]
# Either kind of BCC should work as a linker
# linker = "sparc-gaisler-elf-gcc"
linker = "sparc-gaisler-elf-clang"
rustflags = [
    # Tell Rust's LLVM to target the LEON3
    "-Ctarget-cpu=leon3",
    # Which has the optional CAS Atomics available
    "-Ctarget-feature=+leoncasa",
    # Tell Rust our linker is a gcc compatible C Compiler
    "-Clinker-flavor=gcc",
    # Some Gaisler BCC options we want rustc to pass to the linker
    "-Clink-arg=-mcpu=leon3",
    "-Clink-arg=-qbsp=leon3",
]
runner = "tsim-leon3 -c sim-commands.txt"

[build]
target = ["sparc-unknown-none-elf"]

[unstable]
build-std = ["core"]
