# The JSON target
[target.sparc-unknown-none]
# Either tool should work as a linker
linker = "sparc-gaisler-elf-clang"
# linker = "sparc-gaisler-elf-gcc"
runner = "tsim-leon3 -c sim-commands.txt"

# Settings for a possible future built-in target
# 
[target.sparc-unknown-none-elf]
# Either tool should work as a linker
# linker = "sparc-gaisler-elf-clang"
linker = "sparc-gaisler-elf-gcc"
runner = "tsim-leon3 -c sim-commands.txt"

[build]
# Switch to possible future built-in target
# target = ["sparc-unknown-none-elf"]
target = ["sparc-unknown-none.json"]
rustflags = "-Ctarget-cpu=leon3"

[unstable]
build-std = ["core"]
